### ISSUE TITLE
Setting max-width:100% and width attr in IE8 collapses img

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#363]
wdn / templates_3.1 / less / content / maincontent.less 

``` css
#maincontent img, #maincontent video, #maincontent audio {
  max-width: 100%;
  height: auto;
}
```

propose adding:

``` css
.ie8 #maincontent img {
  max-width: none;
}
```
