### ISSUE TITLE
Remove use of #maincontent as a prefix

### ISSUE THREAD

**Issue by ericras** [unl/wdntemplates#379]
It's difficult to integrate the templates with third party css (Drupal, other things I can't think of at the moment) when rules like "#maincontent a { }" force themselves to the top.

We get things like:

``` css
/* wdn */
#maincontent ul {padding: x;}

/* drupal */
ul.book-menu {padding: y;}

/* wdn/drupal */
ul {padding: 0;}
```

And then there's a messy workaround to prefix ul.book-menu with #maincontent or adding !important.

In my opinion there shouldn't be any rules that include #maincontent except for rules targeting the #maincontent div specifically (padding, margin, border, whatever).

Default styling in the maincontent area should be hit with general a, ul, li rules and mods to other regions should then be prefixed with #header, #navigation, #footer, etc.

A change like this is probably something that will have to wait for some future major release but I may start taking a look at how big the impact would be.
